### ISSUE TITLE
MaplibreLegendControl for UMD version is not constructor.

### ISSUE THREAD

**Issue by smellman** [watergis/maplibre-gl-legend#11]
**Describe the bug**
MaplibreLegendControl for UMD version is not constructor.

**To Reproduce**
1. Download html from https://gist.github.com/smellman/5a1ff75bd877eb62025c44a5cb0e75be
2. Open html file in your browser.
3. See error in debug tool

**Expected behavior**
It to be a constructor.

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: firefox 113.0.2, Google chrome 113.0.5672.126

**Comment by Captain-Oski** [comment]
I support this Issue, 
![image](https://github.com/watergis/maplibre-gl-legend/assets/7432894/4283e7d5-ca26-48ba-9c9e-133e6a8f24db)

**Comment by JinIgarashi** [comment]
@smellman and @Captain-Oski , I am very sorry for inconvenience. README's usage of CDN was wrong, it missed module name of `MaplibreLegendControl.`.

```js
map.addControl(
 					new MaplibreLegendControl.MaplibreLegendControl(targets, {
 						showDefault: true,
 						showCheckbox: true,
 						onlyRendered: true,
 						reverseOrder: true
 					}),
 					'bottom-left'
 				);
```

I also added an example HTML for UMD module (`index_umd.html`). Please check it.
