### ISSUE TITLE
Layer legends don't show up on startup

### ISSUE THREAD

**Issue by geraldo** [watergis/maplibre-gl-legend#5]
Layer legends don't show up on startup, but do appear after checking and unchecking "Only rendered" checkbox and then work like expected. This does happen both with activated and deactivated option `onlyRendered` and is independent of other options.

This happens both on Chrome and Firefox using latest maplibre-gl-js 2.4.0 with maplibre-gl-legend 1.2.7.

PS: Here a [little example](https://linz.pflueckt.at/maplibre-style-tests/) to show this error.

**Comment by JinIgarashi** [comment]
@geraldo I think this was also solved by https://github.com/watergis/maplibre-gl-legend/pull/19. Please check the latest version
