### ISSUE TITLE
404 not found errors in console

### ISSUE THREAD

**Issue by geraldo** [watergis/maplibre-gl-legend#6]
404 not found error do show up in console trying to load `undefined.json` and `undefined@2x.png`:

> GET http://127.0.0.1:5500/undefined.json 404 (Not Found) 
> GET http://127.0.0.1:5500/undefined@2x.png 404 (Not Found)
> Uncaught (in promise) i {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}

This so doesn't seem to have any negative effect on the functions of the plugin, but each interaction with the legend checkboxes do again show these errors.

This happens both on Chrome and Firefox using latest maplibre-gl-js 2.4.0 with maplibre-gl-legend 1.2.7.

PS: Here a [little example](https://linz.pflueckt.at/maplibre-style-tests/) to show this error.

**Comment by JinIgarashi** [comment]
@geraldo I think this was solved by https://github.com/watergis/maplibre-gl-legend/pull/19. Could you check the latest version. Feel free to reopen the issue if bug is still there
